admin_volt/urls.py
from django.urls import path
from admin_volt import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    # Index
   

    # Pages
   
    path('pages/transaction/', views.transaction, name="transaction"),
    path('pages/settings/', views.settings, name="settings"),

    # Tables
    path('tables/bs-tables/', views.bs_tables, name="bs_tables"),

    # Components
    path('components/buttons/', views.buttons, name="buttons"),
    path('components/notifications/', views.notifications, name="notifications"),
    path('components/forms/', views.forms, name="forms"),
    path('components/modals/', views.modals, name="modals"),
    path('components/typography/', views.typography, name="typography"),

    # Authentication
    path('accounts/register/', views.register_view, name="register"),
    path('accounts/login/', views.UserLoginView.as_view(), name="login"),
    path('accounts/logout/', views.logout_view, name="logout"),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password-change-done.html'
    ), name="password_change_done"),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
        views.UserPasswrodResetConfirmView.as_view(), name="password_reset_confirm"
    ),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password-reset-done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password-reset-complete.html'
  ), name='password_reset_complete'),

    path('accounts/lock/', views.lock, name="lock"),

    # Errors
    path('error/404/', views.error_404, name="error_404"),
    path('error/500/', views.error_500, name="error_500"),
    path('admin_change-password/', auth_views.PasswordChangeView.as_view(), name='admin_password_change'),
    path('admin-password-changed/', views.password_change_done, name='admin_password_change_done'),
    path('charts/', views.user_chart_view, name='charts'),
    path('logged_in_users/', views.logged_in_users, name='logged_in_users'),
    path('chart/', views.chart, name='chart'),
    path('get_traffic_data/', views.get_traffic_data, name='get_traffic_data'),
    path('get_social_account_data/', views.get_social_account_data, name='get_social_account_data'),
  
]

home/urls.py
from django.urls import path
# from .views import home, page_privacy_policy, page_terms_and_condition,page_about_us
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home, name="home"),
    path("about-us/", views.about_us, name="about_us"),    
    path("careers/", views.careers, name="careers"),
    path("daily-downloads/", views.daily_downloads, name="daily_downloads"),
    path("legal-framework/", views.legal_framework, name="legal_framework"),
    path("the-exchange/", views.the_exchange, name="the_exchange"),
    path("market-summary/", views.market_summary, name="market_summary"),
    path("media-center/", views.media_center, name="media_center"),
    path("privacy-policy/", views.page_privacy_policy, name="privacy_policy"),
    path("terms-and-conditions/", views.page_terms_and_condition, name="terms_and_condition"),
    path('contact-us/',views.contact_us,name='contact_us'), 
    path('features/',views.features,name='features'),
]

master/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from settings.views import user_settings, password_change_done
from users.views import chart_view, send_mass_message
from django.contrib.auth import views as auth_views
from admin_volt import views
from users.admin import UserProfileAdmin 
from admin_volt.views import chart, get_social_account_data
site_name = 'priority-gold-plus'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-', include('admin_volt.urls')),
    path('send_mass_message/', send_mass_message, name='send_mass_message'),
    path("", include("home.urls", namespace="home")),
    path("api/", include("api_modules.urls", namespace='api')),
    path("users/", include("users.urls", namespace="users")),
    path('password/reset/done/', auth_views.PasswordResetCompleteView.as_view(extra_context={'site_name': site_name}), name='password_reset_from_key_done'),
    path("users-settings/", user_settings, name="users-settings"),
    path("accounts/", include("allauth.urls")),
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    path('user-settings/', include('settings.urls', namespace='settings')),
    path("modules/", include("modules.urls")),
    path('change-password/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-changed/', password_change_done, name='password_change_done'),
    path('charts/', views.user_chart_view, name='charts'),
    path('logged_in_users/', views.logged_in_users, name='logged_in_users'),
    path('chart/', views.chart, name='chart'),
    path('get_traffic_data/', views.get_traffic_data, name='get_traffic_data'),
    path('get_social_account_data/', get_social_account_data, name='get_social_account_data'),
   

]


# Add the media URL for development only
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = "users"
urlpatterns = [
    # path("~signup/", SignUpView.as_view(), name="signup"),
    path("sign-up/", views.sign_up, name="sign_up"),
    # path("signup/", views.user_registration_view, name="signup"),
    path("staff-signup/", views.staff_registration_view, name="staff_signup"),
    path("admin-signup/", views.admin_registration_view, name="admin_signup"),
    path("user-profile/", views.profile_view, name="user_profile"),
    path("edit-user-profile/", views.edit_profile, name="edit_profile"),
    path("~redirect/", view=views.user_redirect_view, name="redirect"),
    path("~update/", view=views.user_update_view, name="update"),
    path("<str:username>/", view=views.user_detail_view, name="detail"),
    # path("<str:username>/", view=portfolio , name="portfolio"),
    path('otp-verification/<str:uidb64>/<str:token>/', views.opt_verification_view.as_view(), name='user_otp_verification'),
    path('resend_otp/<str:uidb64>/<str:token>/', view=views.resend_otp, name='user_resend_otp'),
    path("jbplaccountsetting/", views.settings_view, name="accountsetting"),
    path('portfolio/',views.portfolio,name='portfolio'),
    path('portfolio-main/',views.portfolio_main,name='portfolio_main'),
    # path('view-profile/',views.view_profile_view,name='view_profile'),
    path('add-metal-form/',views.add_metal_form,name='add_metal_form'),

]
    
    
    

admin_volt/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UsernameField, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class RegistrationForm(UserCreationForm):
  password1 = forms.CharField(
      label=_("Password"),
      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
  )
  password2 = forms.CharField(
      label=_("Confirm Password"),
      widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
  )

  class Meta:
    model = User
    fields = ('username', 'email', )

    widgets = {
      'username': forms.TextInput(attrs={
          'class': 'form-control',
          'placeholder': 'Username'
      }),
      'email': forms.EmailInput(attrs={
          'class': 'form-control',
          'placeholder': 'example@company.com'
      })
    }


class LoginForm(AuthenticationForm):
  username = UsernameField(label=_("Your Username"), widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Username"}))
  password = forms.CharField(
      label=_("Your Password"),
      strip=False,
      widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}),
  )

class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))

class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")
    

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Old Password'
    }), label='Old Password')
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")

admin_volt/templates/accounts/forgot-password.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

    <!-- Section -->
    <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
        <div class="container">
            <div class="row justify-content-center form-bg-image">
                <p class="text-center"><a href="{% url 'login' %}" class="d-flex align-items-center justify-content-center">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                    Back to log in
                    </a>
                </p>
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="signin-inner my-3 my-lg-0 bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
                        <h1 class="h3">Forgot your password?</h1>
                        <p class="mb-4">Don't fret! Just type in your email and we will send you a code to reset your password!</p>
                        <form method="post">
                          {% csrf_token %}
                          
                            <!-- Form -->
                            <div class="mb-4">
                                <label for="email">Your Email</label>
                                <div class="input-group">
                                    <input type="email" name="{{form.email.name}}" class="form-control" id="email" placeholder="john@company.com" required autofocus>
                                </div>  
                            </div>
                            <!-- End of Form -->
                            <div class="d-grid">
                                <button type="submit" class="btn btn-gray-800">Recover password</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

admin_volt/templates/accounts/lock.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

  <!-- Section -->
  <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
    <div class="container">
      <a href="{% url 'dashboard' %}" class="d-flex align-items-center justify-content-center mb-4">
        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
            clip-rule="evenodd"></path>
        </svg>
        Back to homepage
      </a>
      <div class="row justify-content-center form-bg-image"
        data-background-lg="{% static 'assets/img/illustrations/signin.svg' %}">
        <div class="col-12 d-flex align-items-center justify-content-center">
          <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
            <div class="text-center text-md-center mb-4 mt-md-0">
              <div class="avatar avatar-lg mx-auto mb-3"><img class="rounded-circle" alt="Image placeholder"
                  src="{% static 'assets/img/team/profile-picture-3.jpg' %}"></div>
              <h1 class="h3">Bonnie Green</h1>
              <p class="text-gray">Better to be safe than sorry.</p>
            </div>
            <form class="mt-5">
              <!-- Form -->
              <div class="form-group mb-4">
                <label for="password">Your Password</label>
                <div class="input-group">
                  <span class="input-group-text" id="basic-addon2">
                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                        d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                        clip-rule="evenodd"></path>
                    </svg>
                  </span>
                  <input type="password" placeholder="Password" class="form-control" id="password" required>
                </div>
              </div>
              <!-- End of Form -->
              <div class="d-grid mt-3">
                <button type="submit" class="btn btn-gray-800">Unlock</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

admin_volt/templates/accounts/password-change-done.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<!-- Section -->
<section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
  <div class="container">
    <div class="row justify-content-center form-bg-image">
      <p class="text-center"><a href="{% url 'dashboard' %}" class="d-flex align-items-center justify-content-center">
          <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
              clip-rule="evenodd"></path>
          </svg>
          Back to Dashboard
        </a>
      </p>
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
          <h1 class="h3 mb-4">Password Change Successfully</h1>
          <div>
            Your password has been changed successfully.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

admin_volt/templates/accounts/password-change.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<!-- Section -->
<section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
  <div class="container">
    <div class="row justify-content-center form-bg-image">
      <p class="text-center"><a href="{% url 'dashboard' %}" class="d-flex align-items-center justify-content-center">
          <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
              clip-rule="evenodd"></path>
          </svg>
          Back to Dashboard
        </a>
      </p>
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
          <h1 class="h3 mb-4">Reset password</h1>
          <form method="post">
            {% csrf_token %}

            <!-- Form -->
            <div class="form-group mb-4">
              <label for="password">{{ form.old_password.label }}</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon2">
                  <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                      d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                      clip-rule="evenodd"></path>
                  </svg>
                </span>
                {{ form.old_password }}
              </div>
            </div>
            <div class="text-danger my-3">{{ form.old_password.errors }}</div>
            <!-- End of Form -->
            <!-- Form -->
            <div class="form-group mb-4">
              <label for="password">{{ form.new_password1.label }}</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon2">
                  <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                      d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                      clip-rule="evenodd"></path>
                  </svg>
                </span>
                {{ form.new_password1 }}
              </div>
            </div>
            <div class="text-danger my-3">{{ form.new_password1.errors }}</div>
            <!-- End of Form -->
            <!-- Form -->
            <div class="form-group mb-4">
              <label for="confirm_password">{{ form.new_password2.label }}</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon2">
                  <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                      d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                      clip-rule="evenodd"></path>
                  </svg>
                </span>
                {{ form.new_password2 }}
              </div>
            </div>
            <div class="text-danger my-3">{{ form.new_password2.errors }}</div>
            <!-- End of Form -->
            <div class="d-grid">
              <button type="submit" class="btn btn-gray-800">Change password</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

admin_volt/templates/accounts/password-reset-complete.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<!-- Section -->
<section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
  <div class="container">
    <div class="row justify-content-center form-bg-image">
      <p class="text-center"><a href="{% url 'login' %}" class="d-flex align-items-center justify-content-center">
          <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
              clip-rule="evenodd"></path>
          </svg>
          Back to Login
        </a>
      </p>
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
          <h1 class="h3 mb-4">Password Reset</h1>
          <div>
            Your password has been reset successfully. Login again.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

admin_volt/templates/accounts/password-reset-done.html
{% extends 'layouts/base-auth.html' %}
{% load static %}

{% block content %}

<!-- Section -->
<section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
  <div class="container">
    <div class="row justify-content-center form-bg-image">
      <p class="text-center"><a href="{% url 'login' %}" class="d-flex align-items-center justify-content-center">
          <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
              clip-rule="evenodd"></path>
          </svg>
          Back to Login
        </a>
      </p>
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
          <h1 class="h3 mb-4">Email Sent</h1>
          <div>
            An email has been sent to your email address. Please click the link and reset your password.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

admin_volt/templates/accounts/sign-up.html
{% extends "account/base.html" %}
{% load bootstrap5 %}
{% load i18n %}
{% load static %}
{% comment %} {% block head_title %}{% trans "User Registration | Priority Gold Plus" %}{% endblock %} {% endcomment %}
{% block head_title %}{{ head_title }}{% endblock %}
{% block head_custom_css %}
<link rel="stylesheet" type="text/css" href={% static 'css/signup.css' %}>
{% endblock %}

{% block content %}
    <div class="back-button">
        <a href="/"><img src={% static 'img/back-button.png' %} alt="back"></a>
    </div>
    <div class="back-heading">Back</div>


    <div class="container container-sign">
        <div class="col-lg-5">
            <div class="left-section">
                <div class="logo">
                    <img src={% static 'img/group-8.svg' %} alt="Logo">
                </div>
                <div class="form">
                    <h2>{% trans "Create an Account" %}</h2>
                    <p>{% trans "Please fill the form to create you account." %}</p>
                    <form class="login" method="POST" method="POST" action="{% url 'users:sign_up'%}">
                        {% csrf_token %}

                        {% comment %} <div class="form-group" style=" margin-bottom: 0px;">
                            <label class="form-label-email">{{form.username.label}}</label>
                            {{form.username}}
                        </div> {% endcomment %}

                        {% comment %} <div class="form-group" style=" margin-bottom: 0px;">
                        <label class="form-label-email">{{form.email.label}}</label>
                        {{form.email}}
                        </div> {% endcomment %}
                        <div class="form-group"><label class="form-label" for="id_email">Email Address*</label><input type="email" name="email" placeholder="example@domain.com" autocomplete="email" class="form-control" title="" required id="id_email"></div>
                        <div class="form-group"><label class="form-label" for="id_password1">Password*</label><input type="password" id="password1" name="password1" autocomplete="new-password" class="form-control" placeholder="**********" title="Your password can’t be too similar to your other personal information.Your password must contain at least 6 characters.Your password can’t be a commonly used password.Your password can’t be entirely numeric." required id="id_password1">
                            <span class="eye" onclick="togglePasswordVisibility('password1', 'hide1', 'hide2')">
                                <i id="hide1" class="fa fa-eye"></i>
                                <i id="hide2" class="fa fa-eye-slash"></i>
                            </span>
                            {% comment %} <small class="form-text text-muted"><ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 6 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></small>                                                 {% endcomment %}
                        </div>

                        {% comment %} {% bootstrap_field form.password1 form_group_class='form-group' %} {% endcomment %}
                        {% comment %} {% bootstrap_field form.password2 form_group_class='form-group' %} {% endcomment %}

                        <div class="form-group">
                            <label class="form-label" for="id_password2">Re-Type Password</label>
                            <input type="password" name="password2" id="password2" autocomplete="new-password" class="form-control" placeholder="**********" title="Enter the same password as before, for verification." required id="id_password2">
                            {% comment %} <small class="form-text text-muted">Enter the same password as before, for verification.</small>                         {% endcomment %}
                            <span class="eye" onclick="togglePasswordVisibility('password2', 'hide3', 'hide4')">
                                <i id="hide3" class="fa fa-eye"></i>
                                <i id="hide4" class="fa fa-eye-slash"></i>
                            </span>
                        </div>

                        {% comment %} <div class="form-group" style=" margin-bottom: 0px;">
                            <label class="form-label-password">{{form.password1.label}}</label>
                            {{form.password1}}
                            <div class="help-text">{{ form.password1.help_text }}</div>
                        </div> {% endcomment %}
                        {% comment %} <div class="form-group" style=" margin-bottom: 0px;">
                            <label class="form-label-retype-password">{{form.password2.label}}</label>
                            {{form.password2}}
                            <div class="help-text">{{ form.password2.help_text }}</div>
                        </div> {% endcomment %}
                        <div class="checkbox-color">
                            <input type="checkbox" name="terms_of_services" class="custom-checkbox" required id="id_terms_of_services">
                            <label class="mm-checkbox" for="terms_of_services"><a href="{% url 'home:terms_and_condition' %}" target="_blank">{{form.terms_of_services.label}}</a></label>
                        </div>

                        {% comment %} <button class="signup-button">Next</button> {% endcomment %}
                        {% comment %} <input class="signup-button" type="submit" value="Next"> {% endcomment %}
                        <button class="signup-button" type="submit">{% trans "Next" %}</button>
                        <p class="line">Already Have An Account? <a href="{% url 'account_login' %}">Login</a></p>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-7">
            {% comment %} <div class="right-section"><img src={% static 'img/group-12204.png' %}></div> {% endcomment %}
            <div class="right-section"><img src={% static 'img/register-img.png' %}></div>
        </div>
    </div>
    <div class="back">
        <img src={% static 'img/background-eagle.svg' %}>
    </div>

{% endblock %}

    {% block extra_body %}

    <script>
        function togglePasswordVisibility(inputId, showIconId, hideIconId) {
            var x = document.getElementById(inputId);
            var showIcon = document.getElementById(showIconId);
            var hideIcon = document.getElementById(hideIconId);

            if (x.type === 'password') {
                x.type = 'text';
                showIcon.style.display = 'none';
                hideIcon.style.display = 'inline-block';
            } else {
                x.type = 'password';
                showIcon.style.display = 'inline-block';
                hideIcon.style.display = 'none';
            }
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>




    {% endblock %}